-- =============================================================================
--  Repairs topic titles that lost their apostrophes or their capitals
--  during import:
--    bugdoydoshlar -> bug'doydoshlar,  qozgolonlari -> qo'zg'olonlari
--    proper nouns lower-cased: rossiya -> Rossiya
--
--  Only titles are touched, never the relations. Safe to re-run.
--
--    psql -U edu -d edu -f sql/014_topic_titles.sql
-- =============================================================================

BEGIN;

UPDATE topic_translations tt SET title = v.title
FROM (VALUES
    ('law_dtm_practice', 'DTM mashqlari'),
    ('state_and_society', 'Davlat va jamiyat'),
    ('law_theory', 'Huquq nazariyasi'),
    ('state_governance', 'Davlat boshqaruvi'),
    ('offense_and_liability', 'Huquqbuzarlik va javobgarlik'),
    ('minors_rights', 'Voyaga yetmaganlar huquqlari'),
    ('constitution_concept', 'Konstitutsiya tushunchasi'),
    ('constitution_adoption', 'Konstitutsiyaning qabul qilinishi'),
    ('rule_of_law_state', 'Huquqiy davlat'),
    ('state_sovereignty', 'Davlat suvereniteti'),
    ('peoples_power', 'Xalq hokimiyatchiligi'),
    ('constitution_law_supremacy', 'Konstitutsiya va qonun ustuvorligi'),
    ('foreign_policy', 'Tashqi siyosat'),
    ('citizenship_general', 'Fuqarolik asoslari'),
    ('identity_documents', 'Shaxsni tasdiqlovchi hujjatlar'),
    ('citizenship_termination', 'Fuqarolikning bekor bo''lishi'),
    ('compatriots_abroad', 'Chet eldagi vatandoshlar'),
    ('court_procedure', 'Sud jarayoni'),
    ('human_rights_concept', 'Inson huquqlari tushunchasi'),
    ('personal_rights', 'Shaxsiy huquqlar'),
    ('political_rights', 'Siyosiy huquqlar'),
    ('economic_and_cultural_rights', 'Iqtisodiy va madaniy huquqlar'),
    ('social_rights', 'Ijtimoiy huquqlar'),
    ('ecological_rights', 'Ekologik huquqlar'),
    ('guarantee_of_human_rights', 'Inson huquqlari kafolatlari'),
    ('constitutional_duties', 'Konstitutsiyaviy burchlar'),
    ('civil_society', 'Fuqarolik jamiyati'),
    ('supreme_assembly', 'Oliy Majlis'),
    ('president_of_uzbekistan', 'O''zbekiston Respublikasi Prezidenti'),
    ('cabinet_of_ministers', 'Vazirlar Mahkamasi'),
    ('local_government', 'Mahalliy davlat hokimiyati'),
    ('judicial_power', 'Sud hokimiyati'),
    ('legal_terminology', 'Huquqiy atamalar'),
    ('historical_chronology', 'Tarixiy sanalar'),
    ('oceans_natural_geography', 'Okeanlar tabiiy geografiyasi'),
    ('africa', 'Afrika'),
    ('africa_natural_geography', 'Afrika tabiiy geografiyasi'),
    ('africa_population', 'Afrika aholisi'),
    ('africa_conservation', 'Afrika tabiatini muhofaza qilish'),
    ('africa_history', 'Afrika tarixi'),
    ('africa_hydrology', 'Afrika ichki suvlari'),
    ('atlantic_ocean', 'Atlantika okeani'),
    ('indian_ocean', 'Hind okeani'),
    ('australia_oceania', 'Avstraliya va Okeaniya'),
    ('oceania', 'Okeaniya'),
    ('pacific_ocean', 'Tinch okeani'),
    ('antarctica', 'Antarktida'),
    ('south_america', 'Janubiy Amerika'),
    ('north_america', 'Shimoliy Amerika'),
    ('north_america_relief', 'Shimoliy Amerika relyefi'),
    ('cordillera', 'Kordilyera'),
    ('appalachian_mountains', 'Appalachi tog''lari'),
    ('rivers', 'Daryolar'),
    ('north_america_lakes', 'Shimoliy Amerika ko''llari'),
    ('arctic_climate', 'Arktika iqlimi'),
    ('antarctic_climate', 'Antarktika iqlimi'),
    ('subarctic_climate', 'Subarktika iqlimi'),
    ('temperate_climate', 'Mo''''tadil iqlim'),
    ('arctic_ocean', 'Shimoliy Muz okeani'),
    ('eurasia', 'Yevrosiyo'),
    ('eurasia_natural_regions', 'Yevrosiyo tabiiy o''lkalari'),
    ('south_east_asia', 'Janubi-Sharqiy Osiyo'),
    ('east_asia', 'Sharqiy Osiyo'),
    ('south_china_highlands', 'Janubiy Xitoy tog''liklari'),
    ('south_asia', 'Janubiy Osiyo'),
    ('central_asia_relief', 'Markaziy Osiyo relyefi'),
    ('himalayas', 'Himolay tog''lari'),
    ('south_asia_relief', 'Janubiy Osiyo relyefi'),
    ('indo_gangetic_plain', 'Hind-Gang tekisligi'),
    ('indus_valley', 'Hind daryosi vodiysi'),
    ('ganges_valley', 'Gang daryosi vodiysi'),
    ('thar_desert', 'Tar cho''li'),
    ('south_asia_rivers', 'Janubiy Osiyo daryolari'),
    ('indian_peninsula', 'Hindiston yarim oroli'),
    ('old_asia', 'Qadimgi Osiyo'),
    ('great_china_plain', 'Buyuk Xitoy tekisligi'),
    ('eurasia_atlas', 'Yevrosiyo atlasi'),
    ('uzbekistan_geographical_position_and_administrative_structure', 'O''zbekistonning geografik o''rni va ma''muriy tuzilishi'),
    ('uzbekistan_natural_conditions_and_resources', 'O''zbekiston tabiiy sharoiti va resurslari'),
    ('uzbekistan_population_and_labor_resources', 'O''zbekiston aholisi va mehnat resurslari'),
    ('uzbekistan_national_economy_structure', 'O''zbekiston xalq xo''jaligi tarkibi'),
    ('fuel_and_energy_complex', 'Yoqilg''i-energetika majmuasi'),
    ('metallurgy_complex', 'Metallurgiya majmuasi'),
    ('machine_building_complex', 'Mashinasozlik majmuasi'),
    ('wood_processing_and_building_materials', 'Yog''ochsozlik va qurilish materiallari'),
    ('ecological_problems', 'Ekologik muammolar'),
    ('agro_industrial_complex_and_agriculture', 'Agrosanoat majmuasi va qishloq xo''jaligi'),
    ('agro_industrial_complex', 'Agrosanoat majmuasi'),
    ('animal_husbandry', 'Chorvachilik'),
    ('sericulture', 'Pillachilik'),
    ('fishing_and_poultry', 'Baliqchilik va parrandachilik'),
    ('fur_farming', 'Mo''ynachilik'),
    ('technical_crops', 'Texnik ekinlar'),
    ('agricultural_specialization', 'Qishloq xo''jaligi ixtisoslashuvi'),
    ('crop_production', 'Dehqonchilik'),
    ('irrigation_agriculture', 'Sug''orma dehqonchilik'),
    ('desert_agriculture', 'Cho''l dehqonchiligi'),
    ('pasture_livestock', 'Yaylov chorvachiligi'),
    ('suburban_agriculture', 'Shahar atrofi qishloq xo''jaligi'),
    ('light_and_food_industry', 'Yengil va oziq-ovqat sanoati'),
    ('cotton_processing', 'Paxta tozalash sanoati'),
    ('light_industry', 'Yengil sanoat'),
    ('fiber_industry', 'To''qimachilik sanoati'),
    ('leather_industry', 'Charm sanoati'),
    ('footwear_industry', 'Poyabzal sanoati'),
    ('traditional_crafts', 'An''anaviy hunarmandchilik'),
    ('food_industry', 'Oziq-ovqat sanoati'),
    ('transport_geography', 'Transport geografiyasi'),
    ('geography_science_development', 'Geografiya fanining rivojlanishi'),
    ('solar_system', 'Quyosh sistemasi'),
    ('earth_solar_system', 'Yer va Quyosh sistemasi'),
    ('astronomy_basics', 'Astronomiya asoslari'),
    ('earth', 'Yer'),
    ('earth_history', 'Yer tarixi'),
    ('cartography', 'Kartografiya'),
    ('geography_basics', 'Geografiya asoslari'),
    ('earth_structure', 'Yerning ichki tuzilishi'),
    ('physical_geography', 'Tabiiy geografiya'),
    ('earth_motion', 'Yerning harakati'),
    ('climate', 'Iqlim'),
    ('measurement', 'O''lchashlar'),
    ('regional_geography', 'Mintaqaviy geografiya'),
    ('calculation', 'Hisoblashlar'),
    ('thematic_maps', 'Mavzuli xaritalar'),
    ('history_of_geography', 'Geografiya tarixi'),
    ('earth_system', 'Yer sistemasi'),
    ('geography_science', 'Geografiya fani'),
    ('geography_terms', 'Geografik atamalar'),
    ('earth_materials', 'Tog'' jinslari va minerallar'),
    ('plate_tectonics', 'Litosfera plitalari'),
    ('orography', 'Orografiya'),
    ('natural_hazards', 'Tabiiy ofatlar'),
    ('volcanism', 'Vulqonlar'),
    ('hydrology', 'Gidrologiya'),
    ('earthquakes', 'Zilzilalar'),
    ('coordinates', 'Geografik koordinatalar'),
    ('geomorphology', 'Geomorfologiya'),
    ('continents', 'Materiklar'),
    ('hydrography', 'Gidrografiya'),
    ('islands', 'Orollar'),
    ('landforms', 'Relyef shakllari'),
    ('mountains', 'Tog''lar'),
    ('lithosphere', 'Litosfera'),
    ('world_geography', 'Jahon geografiyasi'),
    ('natural_resources', 'Tabiiy resurslar'),
    ('uzbekistan_geography', 'O''zbekiston geografiyasi'),
    ('hydrosphere', 'Gidrosfera'),
    ('atmosphere', 'Atmosfera'),
    ('biosphere', 'Biosfera'),
    ('atlas', 'Atlas'),
    ('1991-2017-yillarda Rossiya Federatsiyasi', '1991–2017-yillarda Rossiya Federatsiyasi'),
    ('1991-2017-yillarda Ukraina, Belarus va Moldova respublikalari', '1991–2017-yillarda Ukraina, Belarus va Moldova respublikalari'),
    ('1991-2017-yillarda Kavkazorti davlatlari', '1991–2017-yillarda Kavkazorti davlatlari'),
    ('1991-2017-yillarda Markaziy Osiyo davlatlari', '1991–2017-yillarda Markaziy Osiyo davlatlari'),
    ('1991-2017-yillarda Germaniya Federativ Respublikasi', '1991–2017-yillarda Germaniya Federativ Respublikasi'),
    ('1991-2017-yillarda Buyuk Britaniya', '1991–2017-yillarda Buyuk Britaniya'),
    ('1991-2017-yillarda Fransiya', '1991–2017-yillarda Fransiya'),
    ('1991-2017-yillarda Italiya', '1991–2017-yillarda Italiya'),
    ('1991-2017-yillarda Xitoy Xalq Respublikasi', '1991–2017-yillarda Xitoy Xalq Respublikasi'),
    ('1991-2017-yillarda Yaponiya', '1991–2017-yillarda Yaponiya'),
    ('Sharqiy Yevropa mamlakatlarida demokratik inqiloblar va sotsialistik lagerning parchalanishi', 'Sharqiy Yevropa mamlakatlarida demokratik inqiloblar va sotsialistik lagerning parchalanishi'),
    ('Yangi mingyillik boshlarida jahon sivilizatsiyasi muammolari', 'Yangi mingyillik boshlarida jahon sivilizatsiyasi muammolari'),
    ('hindiston_va_turkiya_1991_2017', 'Hindiston va Turkiya (1991–2017)'),
    ('eron_pokiston_afgoniston_1991_2017', 'Eron, Pokiston, Afg''oniston (1991–2017)'),
    ('suriya_iroq_isroil_falastin_1991_2017', 'Suriya, Iroq, Isroil, Falastin (1991–2017)'),
    ('lotin_amerikasi_afrika_1991_2017', 'Lotin Amerikasi va Afrika (1991–2017)'),
    ('globallashuv_barqaror_rivojlanish_iti_1991_2017', 'Globallashuv va barqaror rivojlanish (1991–2017)'),
    ('amerika_mamlakatlari_aqsh_kanada_braziliya', 'Amerika mamlakatlari: AQSh, Kanada, Braziliya'),
    ('vi_vii_asrlar_madaniy_hayot', 'VI–VII asrlar madaniy hayoti'),
    ('amir_temur_davlati', 'Amir Temur davlati')
) AS v(code, title)
JOIN topics t ON t.code = v.code
WHERE tt.topic_id = t.id AND tt.lang = 'uz-Latn';

-- ---- B: tutuq belgisi tuzatishlari -----------------------------------------
UPDATE topic_translations SET title =
    replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(title, 'Ozbekiston', 'O''zbekiston'), 'ozbekiston', 'o''zbekiston'), 'Ozbek', 'O''zbek'), 'ozbek', 'o''zbek'), 'Osimlik', 'O''simlik'), 'osimlik', 'o''simlik'), 'Bugdoy', 'Bug''doy'), 'bugdoy', 'bug''doy'), 'Qozgolon', 'Qo''zg''olon'), 'qozgolon', 'qo''zg''olon'), 'Topgul', 'To''pgul'), 'topgul', 'to''pgul'), 'Qoshimcha', 'Qo''shimcha'), 'qoshimcha', 'qo''shimcha'), 'Boyicha', 'Bo''yicha'), 'boyicha', 'bo''yicha'), 'Bolaklari', 'Bo''laklari'), 'bolaklari', 'bo''laklari'), 'Boglanish', 'Bog''lanish'), 'boglanish', 'bog''lanish'), 'Yigindi', 'Yig''indi'), 'yigindi', 'yig''indi'), 'Qoshish', 'Qo''shish'), 'qoshish', 'qo''shish'), 'Nomalum', 'Noma''lum'), 'nomalum', 'noma''lum'), 'Manaviy', 'Ma''naviy'), 'manaviy', 'ma''naviy'), 'Talim', 'Ta''lim'), 'talim', 'ta''lim'), 'Meyor', 'Me''yor'), 'meyor', 'me''yor'), 'Sanat', 'San''at'), 'sanat', 'san''at'), 'Memorchilik', 'Me''morchilik'), 'memorchilik', 'me''morchilik'), 'Ilmfan', 'Ilm-fan'), 'ilmfan', 'ilm-fan'), 'Kopayish', 'Ko''payish'), 'kopayish', 'ko''payish'), 'Urugianish', 'Urug''lanish'), 'urugianish', 'urug''lanish'), 'Urug ', 'Urug'' '), 'urug ', 'urug'' '), 'Qirqbogimlar', 'Qirqbo''g''imlar'), 'qirqbogimlar', 'qirqbo''g''imlar'), 'Yosinlar', 'Yo''sinlar'), 'yosinlar', 'yo''sinlar'), 'Suvotlar', 'Suvo''tlar'), 'suvotlar', 'suvo''tlar'), 'Ortasr', 'O''rta asr'), 'ortasr', 'o''rta asr'), 'Orta ', 'O''rta '), ' orta ', ' o''rta '), 'Qoltigi', 'Qo''ltig''i'), 'qoltigi', 'qo''ltig''i'), 'Fargona', 'Farg''ona'), 'fargona', 'Farg''ona'), 'Mirzachol', 'Mirzacho''l'), 'mirzachol', 'Mirzacho''l'), 'Xojalig', 'Xo''jalig'), 'xojalig', 'xo''jalig'), 'Korsatish', 'Ko''rsatish'), 'korsatish', 'ko''rsatish'), 'Gaznaviylar', 'G''aznaviylar'), 'gaznaviylar', 'G''aznaviylar'), 'Garbiy', 'G''arbiy'), 'garbiy', 'G''arbiy'), 'Mogullar', 'Mo''g''ullar'), 'mogullar', 'Mo''g''ullar'), 'Uygonish', 'Uyg''onish'), 'uygonish', 'uyg''onish'), 'Ozgargan', 'O''zgargan'), 'ozgargan', 'o''zgargan'), 'Toqima', 'To''qima'), 'toqima', 'to''qima'), 'Onli', 'O''nli'), ' onli', ' o''nli'), 'Qollash', 'Qo''llash'), 'qollash', 'qo''llash'), 'Soz ', 'So''z '), ' soz ', ' so''z '), 'Kop ', 'Ko''p '), ' kop ', ' ko''p '), 'Elon', 'E''lon'), 'elon', 'e''lon'), 'Zamburuglar', 'Zamburug''lar'), 'zamburuglar', 'zamburug''lar'), 'Movarounnahrlik', 'Movarounnahrlik'), 'Allomalar', 'Allomalar')
WHERE lang = 'uz-Latn';

COMMIT;

SELECT s.code AS fan,
       count(*) FILTER (WHERE tt.title ~ '^[A-Za-z0-9 ,()-]+$') AS hali_shubhali,
       count(*) AS jami
FROM topics t
JOIN subjects s ON s.id = t.subject_id
JOIN topic_translations tt ON tt.topic_id = t.id AND tt.lang = 'uz-Latn'
GROUP BY s.code ORDER BY 2 DESC;