-- =============================================================================
--
--    Get-Content sql/015_topic_titles_ru.sql | docker compose exec -T db psql -U edu -d edu
--
--  Qayta yugurtirish xavfsiz.
--
--
-- =============================================================================

BEGIN;

INSERT INTO topic_translations (topic_id, lang, title)
SELECT t.id, 'ru', v.title
FROM (VALUES
    ('law_dtm_practice', 'Практика ГЦТ'),
    ('state_and_society', 'Государство и общество'),
    ('law_theory', 'Теория права'),
    ('state_governance', 'Государственное управление'),
    ('offense_and_liability', 'Правонарушение и ответственность'),
    ('minors_rights', 'Права несовершеннолетних'),
    ('constitution_concept', 'Понятие Конституции'),
    ('constitution_adoption', 'Принятие Конституции'),
    ('rule_of_law_state', 'Правовое государство'),
    ('state_sovereignty', 'Государственный суверенитет'),
    ('peoples_power', 'Народовластие'),
    ('constitution_law_supremacy', 'Верховенство Конституции и закона'),
    ('foreign_policy', 'Внешняя политика'),
    ('citizenship_general', 'Основы гражданства'),
    ('identity_documents', 'Документы, удостоверяющие личность'),
    ('citizenship_termination', 'Прекращение гражданства'),
    ('compatriots_abroad', 'Соотечественники за рубежом'),
    ('court_procedure', 'Судебный процесс'),
    ('human_rights_concept', 'Понятие прав человека'),
    ('personal_rights', 'Личные права'),
    ('political_rights', 'Политические права'),
    ('economic_and_cultural_rights', 'Экономические и культурные права'),
    ('social_rights', 'Социальные права'),
    ('ecological_rights', 'Экологические права'),
    ('guarantee_of_human_rights', 'Гарантии прав человека'),
    ('constitutional_duties', 'Конституционные обязанности'),
    ('civil_society', 'Гражданское общество'),
    ('supreme_assembly', 'Олий Мажлис'),
    ('president_of_uzbekistan', 'Президент Республики Узбекистан'),
    ('cabinet_of_ministers', 'Кабинет Министров'),
    ('local_government', 'Местные органы власти'),
    ('judicial_power', 'Судебная власть'),
    ('legal_terminology', 'Юридические термины'),
    ('historical_chronology', 'Исторические даты'),
    ('oceans_natural_geography', 'Физическая география океанов'),
    ('africa', 'Африка'),
    ('africa_natural_geography', 'Физическая география Африки'),
    ('africa_population', 'Население Африки'),
    ('africa_conservation', 'Охрана природы Африки'),
    ('africa_history', 'История Африки'),
    ('africa_hydrology', 'Внутренние воды Африки'),
    ('atlantic_ocean', 'Атлантический океан'),
    ('indian_ocean', 'Индийский океан'),
    ('australia_oceania', 'Австралия и Океания'),
    ('oceania', 'Океания'),
    ('pacific_ocean', 'Тихий океан'),
    ('antarctica', 'Антарктида'),
    ('south_america', 'Южная Америка'),
    ('north_america', 'Северная Америка'),
    ('north_america_relief', 'Рельеф Северной Америки'),
    ('cordillera', 'Кордильеры'),
    ('appalachian_mountains', 'Аппалачи'),
    ('rivers', 'Реки'),
    ('north_america_lakes', 'Озёра Северной Америки'),
    ('arctic_climate', 'Арктический климат'),
    ('antarctic_climate', 'Антарктический климат'),
    ('subarctic_climate', 'Субарктический климат'),
    ('temperate_climate', 'Умеренный климат'),
    ('arctic_ocean', 'Северный Ледовитый океан'),
    ('eurasia', 'Евразия'),
    ('eurasia_natural_regions', 'Природные области Евразии'),
    ('south_east_asia', 'Юго-Восточная Азия'),
    ('east_asia', 'Восточная Азия'),
    ('south_china_highlands', 'Южно-Китайское нагорье'),
    ('south_asia', 'Южная Азия'),
    ('central_asia_relief', 'Рельеф Центральной Азии'),
    ('himalayas', 'Гималаи'),
    ('south_asia_relief', 'Рельеф Южной Азии'),
    ('indo_gangetic_plain', 'Индо-Гангская равнина'),
    ('indus_valley', 'Долина Инда'),
    ('ganges_valley', 'Долина Ганга'),
    ('thar_desert', 'Пустыня Тар'),
    ('south_asia_rivers', 'Реки Южной Азии'),
    ('indian_peninsula', 'Полуостров Индостан'),
    ('old_asia', 'Древняя Азия'),
    ('great_china_plain', 'Великая Китайская равнина'),
    ('eurasia_atlas', 'Атлас Евразии'),
    ('uzbekistan_geographical_position_and_administrative_structure', 'Географическое положение и административное устройство Узбекистана'),
    ('uzbekistan_natural_conditions_and_resources', 'Природные условия и ресурсы Узбекистана'),
    ('uzbekistan_population_and_labor_resources', 'Население и трудовые ресурсы Узбекистана'),
    ('uzbekistan_national_economy_structure', 'Структура народного хозяйства Узбекистана'),
    ('fuel_and_energy_complex', 'Топливно-энергетический комплекс'),
    ('metallurgy_complex', 'Металлургический комплекс'),
    ('machine_building_complex', 'Машиностроительный комплекс'),
    ('wood_processing_and_building_materials', 'Деревообработка и строительные материалы'),
    ('ecological_problems', 'Экологические проблемы'),
    ('agro_industrial_complex_and_agriculture', 'Агропромышленный комплекс и сельское хозяйство'),
    ('agro_industrial_complex', 'Агропромышленный комплекс'),
    ('animal_husbandry', 'Животноводство'),
    ('sericulture', 'Шелководство'),
    ('fishing_and_poultry', 'Рыбоводство и птицеводство'),
    ('fur_farming', 'Пушное звероводство'),
    ('technical_crops', 'Технические культуры'),
    ('agricultural_specialization', 'Специализация сельского хозяйства'),
    ('crop_production', 'Растениеводство'),
    ('irrigation_agriculture', 'Орошаемое земледелие'),
    ('desert_agriculture', 'Пустынное земледелие'),
    ('pasture_livestock', 'Пастбищное животноводство'),
    ('suburban_agriculture', 'Пригородное хозяйство'),
    ('light_and_food_industry', 'Лёгкая и пищевая промышленность'),
    ('cotton_processing', 'Хлопкоочистительная промышленность'),
    ('light_industry', 'Лёгкая промышленность'),
    ('fiber_industry', 'Текстильная промышленность'),
    ('leather_industry', 'Кожевенная промышленность'),
    ('footwear_industry', 'Обувная промышленность'),
    ('traditional_crafts', 'Народные ремёсла'),
    ('food_industry', 'Пищевая промышленность'),
    ('transport_geography', 'География транспорта'),
    ('geography_science_development', 'Развитие географической науки'),
    ('solar_system', 'Солнечная система'),
    ('earth_solar_system', 'Земля в Солнечной системе'),
    ('astronomy_basics', 'Основы астрономии'),
    ('earth', 'Земля'),
    ('earth_history', 'История Земли'),
    ('cartography', 'Картография'),
    ('geography_basics', 'Основы географии'),
    ('earth_structure', 'Внутреннее строение Земли'),
    ('physical_geography', 'Физическая география'),
    ('earth_motion', 'Движение Земли'),
    ('climate', 'Климат'),
    ('measurement', 'Измерения'),
    ('regional_geography', 'Региональная география'),
    ('calculation', 'Вычисления'),
    ('thematic_maps', 'Тематические карты'),
    ('history_of_geography', 'История географии'),
    ('earth_system', 'Система Земли'),
    ('geography_science', 'Географическая наука'),
    ('geography_terms', 'Географические термины'),
    ('earth_materials', 'Горные породы и минералы'),
    ('plate_tectonics', 'Литосферные плиты'),
    ('orography', 'Орография'),
    ('natural_hazards', 'Стихийные бедствия'),
    ('volcanism', 'Вулканизм'),
    ('hydrology', 'Гидрология'),
    ('earthquakes', 'Землетрясения'),
    ('coordinates', 'Географические координаты'),
    ('geomorphology', 'Геоморфология'),
    ('continents', 'Материки'),
    ('hydrography', 'Гидрография'),
    ('islands', 'Острова'),
    ('landforms', 'Формы рельефа'),
    ('mountains', 'Горы'),
    ('lithosphere', 'Литосфера'),
    ('world_geography', 'География мира'),
    ('natural_resources', 'Природные ресурсы'),
    ('uzbekistan_geography', 'География Узбекистана'),
    ('hydrosphere', 'Гидросфера'),
    ('atmosphere', 'Атмосфера'),
    ('biosphere', 'Биосфера'),
    ('atlas', 'Атлас'),
    ('hindiston_va_turkiya_1991_2017', 'Индия и Турция (1991–2017)'),
    ('eron_pokiston_afgoniston_1991_2017', 'Иран, Пакистан, Афганистан (1991–2017)'),
    ('suriya_iroq_isroil_falastin_1991_2017', 'Сирия, Ирак, Израиль, Палестина (1991–2017)'),
    ('lotin_amerikasi_afrika_1991_2017', 'Латинская Америка и Африка (1991–2017)'),
    ('globallashuv_barqaror_rivojlanish_iti_1991_2017', 'Глобализация и устойчивое развитие (1991–2017)')
) AS v(code, title)
JOIN topics t ON t.code = v.code
ON CONFLICT (topic_id, lang) DO NOTHING;

COMMIT;

SELECT lang, count(*) FROM topic_translations GROUP BY lang ORDER BY lang;

SELECT s.code AS fan,
       count(*) FILTER (WHERE tt.lang = 'ru') AS ruscha,
       count(DISTINCT t.id)                   AS mavzu
FROM topics t
JOIN subjects s ON s.id = t.subject_id
LEFT JOIN topic_translations tt ON tt.topic_id = t.id
GROUP BY s.code ORDER BY 2 DESC;
